services:
  traefik:
    image: traefik:v2.11
    container_name: ct2-traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=ct2_ct2-net
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ct2-net

