services:
  evidence-db:
    image: postgres:15-alpine
    container_name: ct2-evidence-db
    environment:
      POSTGRES_DB: evidence
      POSTGRES_USER: evidence
      POSTGRES_PASSWORD: evidence
    ports:
    - 5432:5432
    volumes:
    - evidence-db-data:/var/lib/postgresql/data
    - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U evidence -d evidence || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
    - ct2-net
    restart: unless-stopped
  suppliers-service:
    image: node:20-alpine
    container_name: ct2-suppliers-service
    working_dir: /app
    command:
    - node
    - server.mjs
    environment:
      PORT: '8000'
      HOST: 0.0.0.0
      SERVICE_PREFIX: /api
      API_KEY: ct2-dev-key
      PGHOST: evidence-db
      PGUSER: evidence
      PGPASSWORD: evidence
      PGDATABASE: evidence
      PGPORT: '5432'
    volumes:
    - ../apps/backend/services/supplier-service:/app:ro
    depends_on:
      evidence-db:
        condition: service_healthy
    labels:
    - traefik.enable=true
    - traefik.http.routers.suppliers-api.rule=PathPrefix(`/api`)
    - traefik.http.routers.suppliers-api.entrypoints=web
    - traefik.http.services.suppliers.loadbalancer.server.port=8000
    - traefik.http.routers.suppliers-health.rule=Path(`/health`)
    - traefik.http.routers.suppliers-health.entrypoints=web
    networks:
    - ct2-net
    restart: unless-stopped
  traefik:
    image: traefik:v3.0
    container_name: ct2-traefik
    command:
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    - --api.dashboard=true
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - ct2-net
    profiles:
    - infra
    restart: unless-stopped
  evidence-store:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: ct2-evidence-store
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
    - minio-data:/data
    - minio-config:/root/.minio
    ports:
    - 9000:9000
    - 9001:9001
    networks:
    - ct2-net
    profiles:
    - infra
    restart: unless-stopped
networks:
  ct2-net: null
volumes:
  evidence-db-data: null
  minio-data: null
  minio-config: null
  suppliers_node_modules: null
