http:
  routers:
    api-ts-points-post-override:
      entryPoints: ["web"]                      # :8081 in your setup
      rule: Path(`/api/time-series/points`) && Method(`POST`)
      service: ts-svc
      middlewares: ["ts-add-key-fixed","ts-strip"]
      priority: 23500

  middlewares:
    ts-add-key-fixed:
      headers:
        customRequestHeaders:
          x-api-key: "ct2-dev-key"             # send both casings
          X-API-Key: "ct2-dev-key"
