services:
  ingestion-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.ingest.rule=PathPrefix(`/api/ingest`) || PathPrefix(`/api/ingestion`)
      - traefik.http.services.ingest.loadbalancer.server.port=8000

  emission-factors-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.factors.rule=PathPrefix(`/api/factors`) || PathPrefix(`/api/emission-factors`)
      - traefik.http.services.factors.loadbalancer.server.port=8000

  data-quality-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.dataquality.rule=PathPrefix(`/api/data-quality`) || PathPrefix(`/api/dataquality`)
      - traefik.http.services.dataquality.loadbalancer.server.port=8000

  kpi-calculation-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.kpi.rule=PathPrefix(`/api/kpi`)
      - traefik.http.services.kpi.loadbalancer.server.port=8000

  dashboards-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.dash.rule=PathPrefix(`/api/dash`) || PathPrefix(`/api/dashboards`)
      - traefik.http.services.dash.loadbalancer.server.port=8000

  search-index-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.search.rule=PathPrefix(`/api/search`) || PathPrefix(`/api/search-index`)
      - traefik.http.services.search.loadbalancer.server.port=8000

  jobs-service:
    labels:
      - traefik.enable=true
      - traefik.docker.network=ct2-net
      - traefik.http.routers.jobs.rule=PathPrefix(`/api/jobs`)
      - traefik.http.services.jobs.loadbalancer.server.port=8000
