services:
  evidence-store:
    networks: [ct2-net]   # ensure it's on the same network as Traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.evidence.rule=PathPrefix(`/api/evidence`)
      - traefik.http.routers.evidence.entrypoints=web
      - traefik.http.routers.evidence.priority=6000
      - traefik.http.routers.evidence.middlewares=evidence-strip
      - traefik.http.middlewares.evidence-strip.stripprefix.prefixes=/api/evidence
      - traefik.http.services.evidence.loadbalancer.server.port=8000

networks:
  ct2-net:
    external: true
    name: ct2_ct2-net
