services:
  dashboards-service:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ct2-demo_default"
      - "traefik.http.routers.ui-root.rule=PathPrefix(/)"
      - "traefik.http.routers.ui-root.entrypoints=web"
      - "traefik.http.services.ui-root.loadbalancer.server.port=8000"
    networks:
      - ct2-demo_default

networks:
  ct2-demo_default:
    external: true
    name: ct2-demo_default
