services:
  suppliers-service:
    labels:
      - "traefik.enable=true"

      # New router name so it doesn't inherit old settings
      - "traefik.http.routers.suppliers3.entrypoints=web"
      # Cover health + suppliers + assessments under the app's /api prefix
      - "traefik.http.routers.suppliers3.rule=PathPrefix(`/api/suppliers`) || PathPrefix(`/api/assessments`) || Path(`/api/health`)"
      - "traefik.http.routers.suppliers3.service=suppliers-svc3"

      # Single explicit service to upstream port 8000
      - "traefik.http.services.suppliers-svc3.loadbalancer.server.port=8000"

      # IMPORTANT: no middlewares at all
      # Ensure we're on the same network as Traefik:
      - "traefik.docker.network=ct2-net"

    networks:
      - ct2-net

networks:
  ct2-net:
    external: true
