services:
  traefik:
    image: traefik:2.11
    container_name: ct2-traefik-1
    command:
      - --log.level=INFO
      # entrypoints
      - --entryPoints.web.address=:8081
      - --entryPoints.admin.address=:8090
      # providers
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=ct2_ct2-net
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      # API + dashboard
      - --api=true
      - --api.dashboard=true
    ports:
      - "8081:8081"   # web
      - "8090:8090"   # admin (API/Dashboard)
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - ct2_ct2-net
