# docker-compose.mocks.stack.yml
services:
  report-compiler-service:
    networks: [ct2_ct2-net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.reports.rule=PathPrefix(`/api/reports`)
      - traefik.http.routers.reports.entrypoints=web
      - traefik.http.routers.reports.priority=6000
      - traefik.http.routers.reports.middlewares=reports-strip,rate-reports
      - traefik.http.middlewares.reports-strip.stripprefix.prefixes=/api/reports
      - traefik.http.middlewares.rate-reports.ratelimit.average=50
      - traefik.http.middlewares.rate-reports.ratelimit.burst=25
      - traefik.http.services.reports.loadbalancer.server.port=8000
  time-series-service:
    build: null
    image: node:20-alpine
    container_name: ct2-time-series-service-1
    working_dir: /app
    entrypoint: ["node", "/app/mock-health.mjs"]
    command: []
    environment:
      - SERVICE_NAME=time-series
      - API_PREFIX=/api/time-series
      - PORT=8000
      - SERVICE_VERSION=0.0.1
    volumes:
      - ../tools/mocks/mock-health.mjs:/app/mock-health.mjs:ro
    restart: unless-stopped
    networks: [ct2_ct2-net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.time-series.rule=PathPrefix(`/api/time-series`)
      - traefik.http.routers.time-series.entrypoints=web
      - traefik.http.routers.time-series.priority=6000
      - traefik.http.routers.time-series.middlewares=time-series-strip
      - traefik.http.middlewares.time-series-strip.stripprefix.prefixes=/api/time-series
      - traefik.http.services.time-series.loadbalancer.server.port=8000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/api/time-series/health"]
      interval: 5s
      timeout: 2s
      retries: 10
  emission-factors-service:
    build: null
    image: node:20-alpine
    container_name: ct2-emission-factors-service-1
    working_dir: /app
    entrypoint: ["node", "/app/mock-health.mjs"]
    command: []
    environment:
      - SERVICE_NAME=emission-factors
      - API_PREFIX=/api/emission-factors
      - PORT=8000
      - SERVICE_VERSION=0.0.1
    volumes:
      - ../tools/mocks/mock-health.mjs:/app/mock-health.mjs:ro
    restart: unless-stopped
    networks: [ct2_ct2-net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.emission-factors.rule=PathPrefix(`/api/emission-factors`)
      - traefik.http.routers.emission-factors.entrypoints=web
      - traefik.http.routers.emission-factors.priority=6000
      - traefik.http.routers.emission-factors.middlewares=emission-factors-strip
      - traefik.http.middlewares.emission-factors-strip.stripprefix.prefixes=/api/emission-factors
      - traefik.http.services.emission-factors.loadbalancer.server.port=8000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/api/emission-factors/health"]
      interval: 5s
      timeout: 2s
      retries: 10
  traefik:
    networks: [ct2_ct2-net]
networks:
  ct2_ct2-net:
    driver: bridge
