services:
  evidence-store:
    labels:
      - traefik.enable=true
      # Router
      - traefik.http.routers.evidence.entrypoints=web
      - traefik.http.routers.evidence.rule=PathPrefix(`/api/evidence`)
      - traefik.http.routers.evidence.priority=6000
      - traefik.http.routers.evidence.middlewares=evidence-strip
      # Middleware
      - traefik.http.middlewares.evidence-strip.stripprefix.prefixes=/api/evidence
      # Service
      - traefik.http.services.evidence.loadbalancer.server.port=8000
    networks:
      - ct2_ct2-net

networks:
  ct2_ct2-net:
    name: ct2_ct2-net
