services:
  report-compiler-service:
    labels:
      - traefik.enable=true
      # Router
      - traefik.http.routers.reports.entrypoints=web
      - traefik.http.routers.reports.rule=PathPrefix(`/api/reports`)
      - traefik.http.routers.reports.priority=6000
      - traefik.http.routers.reports.middlewares=reports-strip,rate-reports
      # Middlewares
      - traefik.http.middlewares.reports-strip.stripprefix.prefixes=/api/reports
      - traefik.http.middlewares.rate-reports.ratelimit.average=50
      - traefik.http.middlewares.rate-reports.ratelimit.burst=25
      # Service
      - traefik.http.services.reports.loadbalancer.server.port=8000
    networks:
      - ct2_ct2-net

networks:
  ct2_ct2-net:
    name: ct2_ct2-net
