# DEMO override (additive-only). Keeps all existing services/volumes intact.
# - Adds dashboards-service (builds from ../apps/frontend/dashboards-service).
# - Ensures Traefik loads our file-provider rules (traefik/ct2-dynamic.yml).

services:
  dashboards-service:
    container_name: ct2-demo-dashboards-service-1
    image: ct2-demo-dashboards-service
    build:
      context: ../apps/frontend/dashboards-service   # <-- resolves to D:\CT2\apps\frontend\dashboards-service
      dockerfile: Dockerfile
    profiles: ["demo"]
    restart: unless-stopped
    networks:
      - default
    # No labels needed; routing comes from the Traefik file provider
    # pointing to http://dashboards-service:8000

  traefik:
    # Merge into existing Traefik service (additive)
    volumes:
      - ./traefik/ct2-dynamic.yml:/etc/traefik/dynamic/ct2-dynamic.yml:ro
    command:
      - "--entrypoints.web.address=:8081"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--api.dashboard=true"

networks:
  default:
    # Keep the project default network name stable
    name: ct2-demo_default
