services:
  time-series-service:
    labels:
      - traefik.enable=true

      # General router: /api/time-series/*  (strip prefix)
      - traefik.http.routers.api-ts.rule=PathPrefix(`/api/time-series`)
      - traefik.http.routers.api-ts.entrypoints=web
      - traefik.http.routers.api-ts.middlewares=ts-strip
      - traefik.http.routers.api-ts.service=ts-svc
      - traefik.http.services.ts-svc.loadbalancer.server.port=8000
      - traefik.http.middlewares.ts-strip.stripprefix.prefixes=/api/time-series
      - traefik.http.middlewares.ts-strip.stripprefix.forceSlash=true

      # High-priority POST that injects X-API-Key (and still strips)
      - traefik.http.routers.api-ts-points-post.rule=Path(`/api/time-series/points`) && Method(`POST`)
      - traefik.http.routers.api-ts-points-post.entrypoints=web
      - traefik.http.routers.api-ts-points-post.priority=23000
      - traefik.http.routers.api-ts-points-post.middlewares=ts-add-key,ts-strip
      - traefik.http.routers.api-ts-points-post.service=ts-svc

      # Header middleware
      - traefik.http.middlewares.ts-add-key.headers.customrequestheaders.X-API-Key=ct2-dev-key
