version: '3.8'
services:
  traefik:
    image: traefik:v2.11
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - ./traefik:/etc/traefik
    command: --api.insecure=true --providers.file.directory=/etc/traefik/dynamic

  suppliers-service:
    image: ct2-suppliers-service
    networks:
      - ct2-network

networks:
  ct2-network:
    driver: bridge
