log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":8081"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
    network: "ct2-demo_default"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
